# Generated by Django 4.2.4 on 2024-05-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="history",
            field=models.TextField(blank=True, null=True),
        ),
    ]
