# Generated by Django 4.2.4 on 2024-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_context_alter_chat_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
