# Generated by Django 4.2.4 on 2024-05-26 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_chat_history_messages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
