# Generated by Django 4.2.4 on 2024-05-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_deleted_message_starred"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tokens",
            field=models.IntegerField(default=0),
        ),
    ]
