# Generated by Django 5.0.6 on 2024-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_message_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='no_delete',
            field=models.BooleanField(default=False),
        ),
    ]
